### ISSUE TITLE
[1.19] Forge 41.0.70+ incompatibility

### ISSUE THREAD

**Issue by Saereth** [iChun/PartyParrots#1]
This mod and most of your mods I tested (Ding, better bunnies, party parrots, Better than llamas) all seem to have a similar crash on startup with the new forge changes

```
... 43 more

[11:23:32] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:892) ~[client-1.19-20220607.102129-srg.jar%23247!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23247!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23247!/:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23247!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.98.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/WorldEvent$Load
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:92) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-6.0.0.jar%2378!/:?]
	at me.ichun.mods.partyparrots.common.PartyParrots$Config.registerTwerkHandler(PartyParrots.java:104) ~[PartyParrots-1.19-1.1.0.jar%23213!/:1.1.0]
	at me.ichun.mods.partyparrots.common.PartyParrots$Config.onConfigLoad(PartyParrots.java:91) ~[PartyParrots-1.19-1.1.0.jar%23213!/:1.1.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42) ~[javafmllanguage-1.19-41.0.98.jar%23249!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$1(ModStateProvider.java:67) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:66) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:207) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:207) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$17(ModLoader.java:191) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:191) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:120) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:120) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:102) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.world.WorldEvent$Load
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:92) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-6.0.0.jar%2378!/:?]
	at me.ichun.mods.partyparrots.common.PartyParrots$Config.registerTwerkHandler(PartyParrots.java:104) ~[PartyParrots-1.19-1.1.0.jar%23213!/:1.1.0]
	at me.ichun.mods.partyparrots.common.PartyParrots$Config.onConfigLoad(PartyParrots.java:91) ~[PartyParrots-1.19-1.1.0.jar%23213!/:1.1.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42) ~[javafmllanguage-1.19-41.0.98.jar%23249!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$1(ModStateProvider.java:67) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:66) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:207) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:207) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$17(ModLoader.java:191) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:191) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:120) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:120) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:102) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19-41.0.98-universal.jar%23252!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

I know this isn't a forge stable release yet but I figured I'd report anyway and get it on your radar/help me track it as well.

**Comment by iChun** [comment]
I believe this was fixed ages ago. Thanks for the report! Closing
